version: '3.4'

services:
  jibble.httpapi:
    image: ${DOCKER_REGISTRY-}jibblehttpapi
    build:
      context: .
      dockerfile: src/Jibble.HttpApi/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "jibble"
      ACCEPT_EULA: "Y"
  jibble.web:
    image: ${DOCKER_REGISTRY-}jibbleweb
    build:
      context: .
      dockerfile: src/Jibble.Web/Dockerfile
    depends_on:
      - jibble.httpapi

